### ISSUE TITLE
the result is not good

### ISSUE THREAD

**Issue by zzk88862** [IDEA-Research/T-Rex#36]
![image](https://github.com/IDEA-Research/T-Rex/assets/31311358/84e1c151-bf26-4e4c-92ad-14231bfc24d8)

the result is not good, Did I do something wrong in my steps?

**Comment by Mountchicken** [comment]
Hi @zzk88862 
Thanks for your concern. This is actually a common case. In generic visual prompt mode (cross image), you may need more than one image for visual prompting, since different images may have a large intra-class variation and you need to get this generic visual embedding through multiple visual examples from different images. For example, when using a different prompt image, it works better.
![24891711543168_ pic_hd](https://github.com/IDEA-Research/T-Rex/assets/65173622/3de8522a-301f-4c03-a0af-ffca4d386d34)
