### ISSUE TITLE
About content embedding and universal class token.

### ISSUE THREAD

**Issue by VilisovEvgeny** [IDEA-Research/T-Rex#76]
While reading the article, I didn’t fully understand the idea behind these two embeddings [C and C']. 

Are these embeddings initialized when the model is created and then trained? Or are they created every time we submit a new prompt?

If they are initialized when the model is created and then fit, then it is not entirely clear what the idea is of combining the same embeddings with box embeddings (because as I understand from paper, "initiate a learnable content embedding that is broadcasted K times, denoted as C ∈ RK×D"  this is one embedding ). 
If they are created each time based on the information of the current template, it is not clear for me how this happens?

Which information this embedding contain and from where do they obtain it?

It would be great if you could clarify these points for me. Thanks!

**Comment by Mountchicken** [comment]
Hi @VilisovEvgeny 
Thank you for your question. To address this problem, we first need to understand the inputs of deformable cross-attention. We input two things: a content embedding and a position embedding. The content embedding serves as Q, while the image feature serves as K and V. The position embedding is added to Q. In deformable cross-attention, different Qs will focus on different feature regions in the image to extract the features of those regions.

For visual prompts, users will provide some boxes to indicate the objects they want to detect, and these boxes will serve as the position embedding. However, we still need a content embedding to serve as Q. Therefore, we use a globally learnable content embedding C (nn.Parameters(1,256)). This C will be conditioned on its position embedding to extract object features for the regions.

In the same image, for the same category, users might provide multiple visual prompts. Hence, we need to aggregate the features of different Cs. We introduce a global C', which will use self-attention to reference other Cs and thereby aggregate into a single object feature. The role of C is not crucial by itself, but rather it is conditioned by its position embedding.

**Comment by pisiguiii** [comment]
Thanks for your answer @Mountchicken

As I understand (please  correct me if I'm wrong):  

CAT performs the function of adding positional and content embeddings. That is, after this operation, the size of Q will be equal to (nn.Parameters(1,256)). From the article I understood this as a concatenation, that is, I thought that the final size would be [len(B) + len (nn.Parameters(1,256))]

Still don't understand how does C was obtained. Does it contain any information about image from which we take our prompts, or is it just learnable embedding which was somehow fitted and used as weights?

Does Q from prompt which used to caltulate Q' contain any information extracted from image, from it's features inside chosen regions as promps, when passed as input to deformable attention?

I understand how in formula 4 we extract information from an encoded image, but how Q and feature map relate remains unclear to me and it's mostly because I still don't understand meaning of C. 

Sorry, if i understand something wrong. I will be very grateful if you could clarify this to me

**Comment by VilisovEvgeny** [comment]
Thanks for your answer @Mountchicken

As I understand (please correct me if I'm wrong):

CAT performs the function of adding positional and content embeddings. That is, after this operation, the size of Q will be equal to (nn.Parameters(1,256)). From the article I understood this as a concatenation, that is, I thought that the final size would be [len(B) + len (nn.Parameters(1,256))]

Still don't understand how does C was obtained. Does it contain any information about image from which we take our prompts, or is it just learnable embedding which was somehow fitted and used as weights (that what "gloabl" means?)?

Does Q from prompt which used to caltulate Q' contain any information extracted from image, from it's features inside chosen regions as promps, when passed as input to deformable attention?

I understand how in formula 4 we extract information from an encoded image, but how Q and feature map relate remains unclear to me and it's mostly because I still don't understand meaning of C.

Sorry, if i understand something wrong. I will be very grateful if you could clarify this to me
