### ISSUE TITLE
difference between IVP and GVP

### ISSUE THREAD

**Issue by fuweifuvtoo** [IDEA-Research/T-Rex#79]
refer to issue #71 

When the number of reference image is 1, and the reference image and the target image are different images, is there any difference between interactive visual prompt and generic visual prompt?

I think in this case, IVP == GVP?

**Comment by Mountchicken** [comment]
Hi @fuweifu-vtoo 
Technically there is no difference between them. Given N images (N can be one), we will extract visual prompt embedding from these images and then detect them on other images. In IVP, the prompt image and target image are the same and In GVP, the prompt image and the target image are different.

**Comment by fuweifuvtoo** [comment]
But you comment in issue #71 

"The interactive visual prompt is for the case that the prompt image and target image are the same. When they are not, using generic visual prompt."

Since IVP == GVP in this case（number of reference image is 1, and the reference image and the target image are different images）, why does GVP perform better than IVP?

**Comment by Mountchicken** [comment]
The reason IVP  is used when the prompt image and target image are the same, while GVP is used when the two images are different, is due to the way the API's code logic is implemented. The visual embedding is extracted from image A and detection is performed on image B. In IVP, since the two images are the same, the image encoder only needs to run once, saving computational resources. However, in GVP, the image encoder needs to run twice.
